import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Ez automatikusan elkészíti a menüt a docs/ mappádban lévő meglévő fájlokból
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
